sudo: false
language: scala

scala:
  - 2.12.6
  - 2.11.12
  - 2.13.0-M5

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

jdk:
  - oraclejdk8

before_install:
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION project docs/compile
  - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues
  - sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "ChristopherDavenport/cats-scalacheck" && sbt ++$TRAVIS_SCALA_VERSION publish
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "ChristopherDavenport/cats-scalacheck" && test $TRAVIS_SCALA_VERSION == "2.12.6" && sbt docs/publishMicrosite
